import asyncio
import os
import sys
import types
import pytest

# Ensure a psycopg2 shim is registered before nested conftest modules
# attempt to install placeholder modules (which lack the `connect` API).
try:
    import psycopg2  # type: ignore  # noqa: F401
except Exception:
    pass


def _install_stubs():
    # Stub prometheus_client (CollectorRegistry, Counter, Gauge, Histogram)
    prom = types.ModuleType('prometheus_client')

    class CollectorRegistry:
        def __init__(self, auto_describe=True):
            try:
                self._dummy_names = []
            except Exception:
                pass
        def collect(self):
            out = []
            try:
                names = getattr(self, '_dummy_names', []) or []
                for nm in names:
                    mf = type('MF', (), {'name': nm, 'type': 'gauge', 'samples': []})()
                    out.append(mf)
            except Exception:
                pass
            return out

    class Counter:
        def __init__(self, *args, **kwargs):
            self._value = 0
            try:
                name = args[0] if args else kwargs.get('name')
                registry = kwargs.get('registry')
                if registry is not None:
                    lst = getattr(registry, '_dummy_names', None)
                    if lst is None:
                        lst = []
                        setattr(registry, '_dummy_names', lst)
                    if name not in lst:
                        lst.append(name)
            except Exception:
                pass
        def inc(self, v: float = 1.0):
            try:
                self._value += float(v)
            except Exception:
                pass
        def labels(self, **kwargs):
            return self

    class Gauge:
        def __init__(self, *args, **kwargs):
            self._value = 0
        def set(self, v: float):
            try:
                self._value = float(v)
            except Exception:
                pass
        def labels(self, **kwargs):
            return self

    class Histogram:
        def __init__(self, *args, **kwargs):
            self._values = []
            try:
                name = args[0] if args else kwargs.get('name')
                registry = kwargs.get('registry')
                if registry is not None:
                    lst = getattr(registry, '_dummy_names', None)
                    if lst is None:
                        lst = []
                        setattr(registry, '_dummy_names', lst)
                    if name not in lst:
                        lst.append(name)
            except Exception:
                pass
        def observe(self, v: float):
            try:
                self._values.append(float(v))
            except Exception:
                pass
        def labels(self, **kwargs):
            return self

    def generate_latest(reg=None):
        try:
            reg = reg or CollectorRegistry()
            names = getattr(reg, '_dummy_names', []) or []
            parts = []
            for n in names:
                parts.append(f"# HELP {n} autogenerated")
                parts.append(f"# TYPE {n} gauge")
                parts.append(f"{n} 1")
            return "\n".join(parts).encode('utf-8')
        except Exception:
            return b""

    def start_http_server(port, addr='0.0.0.0'):
        return None

    prom.CollectorRegistry = CollectorRegistry
    prom.Counter = Counter
    prom.Gauge = Gauge
    prom.Histogram = Histogram
    prom.generate_latest = generate_latest
    prom.start_http_server = start_http_server
    sys.modules['prometheus_client'] = prom

# Always provide a lightweight psycopg2 shim to avoid import-time failures
if 'psycopg2' not in sys.modules:
    sys.modules['psycopg2'] = types.ModuleType('psycopg2')
    for sub in ('extras', 'extensions', 'pool'):
        sys.modules.setdefault(f'psycopg2.{sub}', types.ModuleType(f'psycopg2.{sub}'))

    # Stub aiohttp (empty module to satisfy imports in lite mode)
    sys.modules.setdefault('aiohttp', types.ModuleType('aiohttp'))

    # Stub lark essentials used by lightweight tests
    lark = types.ModuleType('lark')

    class Lark:
        def __init__(self, *args, **kwargs):
            pass

    class Transformer:
        pass

    def v_args(*a, **k):
        def _wrap(x):
            return x

        return _wrap

    lark.Lark = Lark
    lark.Transformer = Transformer
    lark.v_args = v_args
    sys.modules.setdefault('lark', lark)


if os.environ.get('PLATFORM_LITE_INIT') in ('1', 'true', 'True'):
    _install_stubs()

# Ensure tests importing top-level `api`, `core`, etc. resolve to `src.*` during collection
PROJECT_ROOT = os.path.dirname(__file__)
SRC_PATH = os.path.join(PROJECT_ROOT, 'src')
if PROJECT_ROOT not in sys.path:
    # Ensure project root is first so local top-level shims (e.g., azure/) are
    # importable during pytest collection and take precedence over installed
    # namespace packages.
    sys.path.insert(0, PROJECT_ROOT)
if SRC_PATH not in sys.path:
    sys.path.insert(0, SRC_PATH)

# Provide lightweight module aliases (e.g., `api.server` -> `src.api.server` resolved via sys.path)

@pytest.fixture
def loop():
    """Compat fixture for aiohttp/pytest-asyncio tests expecting `loop`."""
    loop = asyncio.new_event_loop()
    try:
        yield loop
    finally:
        loop.close()
