// Saved queries, recent decisions (label chips), suppression rules, approvals
            (function(){
                // Saved Queries
                const sqList = document.getElementById('sqList');
                const btnSave = document.getElementById('btnSqSave');
                const btnApply = document.getElementById('btnSqApply');
                const recentBody = document.getElementById('recentDecisionsBody');
                function loadSaved(){
                    try{
                        const raw = localStorage.getItem('savedQueries') || '[]';
                        const arr = JSON.parse(raw);
                        sqList.innerHTML = arr.length ? arr.map((q,i)=> `<div style='display:flex; justify-content:space-between; gap:8px; padding:6px; border-bottom:1px solid var(--border);'><div><strong>${_htmlEsc(q.name||('query '+(i+1)))}</strong><div style='font-size:11px; color:var(--text-muted);'>${_htmlEsc(JSON.stringify(q.filters||{},null,0))}</div></div><div><button class='btn' data-idx='${i}'>Load</button></div></div>`).join('') : '<div style="opacity:.6;">No saved queries</div>';
                        sqList.querySelectorAll('button[data-idx]').forEach(b=> b.addEventListener('click', ()=>{ try{ const idx = Number(b.getAttribute('data-idx')); const raw = localStorage.getItem('savedQueries') || '[]'; const arr = JSON.parse(raw); const q = arr[idx]; if(!q) return; document.getElementById('sqFilterUser').value = q.filters.user||''; document.getElementById('sqFilterHost').value = q.filters.host||''; document.getElementById('sqFilterProc').value = q.filters.process||''; document.getElementById('sqFilterHash').value = q.filters.hash||''; document.getElementById('sqFilterDomain').value = q.filters.domain||''; }catch(_){ } }));
                    }catch(_){ sqList.innerHTML = '<div>Load failed</div>'; }
                }
                function save(){
                    try{
                        const name = document.getElementById('sqName').value.trim() || 'query';
                        const q = { name, filters:{ user:document.getElementById('sqFilterUser').value.trim(), host:document.getElementById('sqFilterHost').value.trim(), process:document.getElementById('sqFilterProc').value.trim(), hash:document.getElementById('sqFilterHash').value.trim(), domain:document.getElementById('sqFilterDomain').value.trim() } };
                        const raw = localStorage.getItem('savedQueries') || '[]'; const arr = JSON.parse(raw); arr.push(q); localStorage.setItem('savedQueries', JSON.stringify(arr)); loadSaved(); showNotification('Query saved','success');
                    }catch(_){ showNotification('Save failed','error'); }
                }
                async function apply(){
                    try{
                        recentBody.innerHTML = '<div style="opacity:.6;">Loading…</div>';
                        const r = await (window.safeFetch||fetch)('/api/v1/decisions/recent?limit=50', { headers: authHeaders() });
                        const j = await r.json().catch(()=>({}));
                        if(!r.ok){ recentBody.innerHTML = '<div>Load failed</div>'; return; }
                        const filters = { user:document.getElementById('sqFilterUser').value.trim(), host:document.getElementById('sqFilterHost').value.trim(), process:document.getElementById('sqFilterProc').value.trim(), file_hash:document.getElementById('sqFilterHash').value.trim(), domain:document.getElementById('sqFilterDomain').value.trim() };
                        const rows = j.decisions || j.rows || j.events || [];
                        const match = (row)=>{ try{ const ctx = row.context || row.hopgraph_context || {}; if(filters.user && (!ctx.user || String(ctx.user).indexOf(filters.user)===-1)) return false; if(filters.host && (!ctx.host || String(ctx.host).indexOf(filters.host)===-1)) return false; if(filters.process && (!ctx.process || String(ctx.process).indexOf(filters.process)===-1)) return false; if(filters.file_hash && (!ctx.file_hash || String(ctx.file_hash).indexOf(filters.file_hash)===-1)) return false; if(filters.domain && (!ctx.domain || String(ctx.domain).indexOf(filters.domain)===-1)) return false; return true; }catch(_){ return true; } };
                        const filtered = rows.filter(match).slice(0,20);
                        recentBody.innerHTML = filtered.length ? filtered.map(d=>{ const conf = (d.confidence!=null)? Number(d.confidence).toFixed(2) : 'n/a'; const cid = d.id || d.event_id || ''; const recs = Array.isArray(d.recommendation_catalog)? d.recommendation_catalog.slice(0,3) : []; const acts = Array.isArray(d.recommendation_actions)? d.recommendation_actions.slice(0,3) : []; const tags = Array.isArray(d.tags)? d.tags.slice(0,6) : []; const iid = d.incident_id || ''; const recHtml = recs.length? `<div style='margin-top:6px; font-size:12px; color:var(--text-muted);'>Recs: ${recs.map(r=>_htmlEsc(r.action||r)).join(', ')}</div>`:''; const actHtml = acts.length? `<div style='margin-top:6px; display:flex; gap:6px; flex-wrap:wrap;'>${acts.map(a=>`<button class='btn' data-rec='${_htmlEsc(a.id||a)}' data-iid='${_htmlEsc(iid)}' title='Mark completed'>Act: ${_htmlEsc(a.id||a)}</button>`).join('')}</div>`:''; return `<div style='border:1px solid var(--border); border-radius:8px; padding:8px; margin-bottom:8px;'><div style='display:flex; justify-content:space-between; gap:8px;'><div><strong>${_htmlEsc(d.verdict||'decision')}</strong> • conf ${_htmlEsc(conf)}</div><div style='display:flex; gap:6px;'><button class='btn' data-act='incident' data-id='${_htmlEsc(cid)}'>Create Incident</button><button class='btn' data-label='tp' data-id='${_htmlEsc(cid)}'>TP</button><button class='btn' data-label='fp' data-id='${_htmlEsc(cid)}'>FP</button></div></div><div style='margin-top:6px;'>${tags.map(t=>`<span class='pill'>${_htmlEsc(t)}</span>`).join(' ')}</div>${recHtml}${actHtml}</div>`; }).join('') : '<div style="opacity:.6;">No decisions</div>';
                        recentBody.querySelectorAll('button[data-act="incident"]').forEach(b=> b.addEventListener('click', ()=> createIncidentFromRecent()));
                        recentBody.querySelectorAll('button[data-label]').forEach(b=> b.addEventListener('click', async ()=>{ const label = b.getAttribute('data-label'); const payload = { observations: { decision: { [label]: 1 } } }; try{ const rr = await (window.safeFetch||fetch)('/api/v1/admin/factors/observations', { method:'POST', headers:{ 'Content-Type':'application/json', ...authHeaders() }, body: JSON.stringify(payload) }); showNotification(rr.ok? 'Labeled' : 'Label sent'); }catch(_){ showNotification('Label failed','error'); } }));
                        recentBody.querySelectorAll('button[data-rec]').forEach(b=> b.addEventListener('click', async ()=>{ try{ let iid = b.getAttribute('data-iid')||''; const actionId = b.getAttribute('data-rec')||''; if(!actionId){ showNotification('No action id','error'); return; } if(!iid){ iid = prompt('Incident ID to update?')||''; } if(!iid){ showNotification('No incident id','error'); return; } const url = `/api/v1/incidents/${encodeURIComponent(iid)}/recommendations/act`; const r = await (window.safeFetch||fetch)(url, { method:'POST', headers:{ 'Content-Type':'application/json', ...authHeaders() }, body: JSON.stringify({ action_id: actionId, status: 'completed', actor: (localStorage.getItem('role')||'analyst') }) }); if(r.ok){ showNotification('Recommendation marked completed','success'); } else { showNotification('Action failed','error'); } }catch(_){ showNotification('Action exception','error'); } }));
                    }catch(_){ recentBody.innerHTML = '<div>Apply failed</div>'; }
                }
                btnSave && btnSave.addEventListener('click', save);
                btnApply && btnApply.addEventListener('click', apply);
                setTimeout(loadSaved, 800);

                // Suppression
                const supList = document.getElementById('supList');
                async function refreshSup(){ try{ const r = await (window.safeFetch||fetch)('/api/v1/admin/suppression/rules', { headers: authHeaders() }); const j = await r.json().catch(()=>({})); if(!r.ok){ supList.innerHTML = '<div>Load failed</div>'; return; } const rows = j.rules || []; supList.innerHTML = rows.length ? rows.map(r=> `<div style='display:flex; justify-content:space-between; gap:8px; padding:6px; border-bottom:1px solid var(--border);'><div><span class='pill'>${_htmlEsc(r.type)}</span> ${_htmlEsc(r.value)} <span style='opacity:.6; font-size:11px;'>${r.expires_ts? ('exp '+(Math.max(0, r.expires_ts - Math.floor(Date.now()/1000)))+'s') : 'no ttl'}</span></div><div><button class='btn' data-del='${_htmlEsc(r.id)}'>Delete</button></div></div>`).join('') : '<div style="opacity:.6;">No rules</div>'; supList.querySelectorAll('button[data-del]').forEach(b=> b.addEventListener('click', async ()=>{ try{ const id = b.getAttribute('data-del'); const rr = await (window.safeFetch||fetch)(`/api/v1/admin/suppression/rules/${encodeURIComponent(id)}`, { method:'DELETE', headers: authHeaders() }); if(rr.ok){ showNotification('Rule deleted','success'); refreshSup(); } else { showNotification('Delete failed','error'); } }catch(_){ showNotification('Delete exception','error'); } })); }catch(_){ supList.innerHTML = '<div>Exception</div>'; } }
                async function addSup(){ try{ const body = { type: document.getElementById('supType').value, value: document.getElementById('supValue').value.trim(), ttl_seconds: Number(document.getElementById('supTTL').value||0)||undefined, reason: document.getElementById('supReason').value.trim(), actor: (localStorage.getItem('actor')||'analyst') }; const r = await (window.safeFetch||fetch)('/api/v1/admin/suppression/rules', { method:'POST', headers:{ 'Content-Type':'application/json', ...authHeaders() }, body: JSON.stringify(body) }); if(r.ok){ showNotification('Rule added','success'); refreshSup(); } else { showNotification('Add failed','error'); } }catch(_){ showNotification('Add exception','error'); } }
                document.getElementById('btnSupAdd')?.addEventListener('click', addSup);
                document.getElementById('btnSupRefresh')?.addEventListener('click', refreshSup);
                setTimeout(refreshSup, 1000);

                // Approvals
                const apList = document.getElementById('apList');
                async function apRefresh(){ try{ const r = await (window.safeFetch||fetch)('/api/v1/admin/approvals', { headers: { ...authHeaders(), 'X-Role': (localStorage.getItem('role')||'analyst') } }); const j = await r.json().catch(()=>({})); if(!r.ok){ apList.innerHTML = '<div>Load failed</div>'; return; } const rows = j.items || []; apList.innerHTML = rows.length ? rows.map(it=> `<div style='display:flex; justify-content:space-between; gap:8px; padding:6px; border-bottom:1px solid var(--border);'><div><strong>${_htmlEsc(it.action)}</strong> • ${_htmlEsc(it.resource)} <span class='pill'>${_htmlEsc(it.status)}</span></div><div>${['pending'].includes(it.status)? `<button class='btn' data-approve='${_htmlEsc(it.id)}'>Approve</button><button class='btn' data-reject='${_htmlEsc(it.id)}'>Reject</button>`:''}</div></div>`).join('') : '<div style="opacity:.6;">No approvals</div>'; apList.querySelectorAll('button[data-approve]').forEach(b=> b.addEventListener('click', ()=> apAct('approve', b.getAttribute('data-approve')))); apList.querySelectorAll('button[data-reject]').forEach(b=> b.addEventListener('click', ()=> apAct('reject', b.getAttribute('data-reject')))); }catch(_){ apList.innerHTML = '<div>Exception</div>'; } }
                async function apAct(kind, id){ try{ const r = await (window.safeFetch||fetch)(`/api/v1/admin/approvals/${encodeURIComponent(id)}/${kind}`, { method:'POST', headers: { ...authHeaders(), 'X-Role': (localStorage.getItem('role')||'analyst') } }); if(r.ok){ showNotification('Updated','success'); apRefresh(); } else { showNotification('Action failed','error'); } }catch(_){ showNotification('Action exception','error'); } }
                async function apRequest(){ try{ const body = { action: document.getElementById('apAction').value.trim(), resource: document.getElementById('apResource').value.trim(), role_required: document.getElementById('apRoleRequired').value, requested_by: (localStorage.getItem('role')||'analyst') }; const r = await (window.safeFetch||fetch)('/api/v1/admin/approvals/request', { method:'POST', headers:{ 'Content-Type':'application/json', ...authHeaders(), 'X-Role': (localStorage.getItem('role')||'analyst') }, body: JSON.stringify(body) }); if(r.ok){ showNotification('Requested','success'); apRefresh(); } else { showNotification('Request failed','error'); } }catch(_){ showNotification('Request exception','error'); } }
                document.getElementById('btnApRequest')?.addEventListener('click', apRequest);
                document.getElementById('btnApRefresh')?.addEventListener('click', apRefresh);
                setTimeout(apRefresh, 1000);
            })();