from pathlib import Path
path = Path('frontend/static/janusec-platform-complete-LIVE.html')
text = path.read_text()
old_options = [
"            const invPanel = document.getElementById('investigationPanel');\n            if (invPanel) invPanel.addEventListener('click', async () => {\n                try {\n                    const r = await (window.safeFetch || fetch)('/api/v1/decisions/recent?limit=1', { headers: authHeaders() });\n                    let j = {};\n                    try{ j = await r.json().catch(()=>({})); }catch(_){ }\n                    if (!r.ok) {\n                        const det = (j && (j.detail || j.error)) ? (j.detail || j.error) : ('HTTP ' + r.status);\n                        showNotification('Failed to fetch recent decisions: ' + det, 'error');\n                        return;\n                    }\n                    const row = j && (j.rows && j.rows[0] || j.events && j.events[0]);\n                    const id = row ? (row.event_id || row.id) : null;\n                    if (id) openInvestigationDetails(id); else showNotification('No recent decision available', 'error');\n                } catch (e) {\n                    showNotification('Failed to open investigation details', 'error');\n                }\n            });\n",
"            const invPanel = document.getElementById('investigationPanel');\n            if (invPanel) invPanel.addEventListener('click', async () => {\n                try {\n                    const r = await (window.safeFetch || fetch)('/api/v1/decisions/recent?limit=1', { headers: authHeaders() });\n                    let j = {};\n                    try{ j = await r.json().catch(()=>({})); }catch(_){ }\n                    if (!r.ok) {\n                        const det = (j && (j.detail || j.error)) ? (j.detail || j.error) : ('HTTP ' + r.status);\n                        showNotification('Failed to fetch recent decisions: ' + det, 'error');\n                        return;\n                    }\n                    const row = j && (j.rows && j.rows[0] || j.events && j.events[0]);\n                    const id = row ? (row.event_id || row.id) : null;\n                    if (id) openInvestigationDetails(id); else showNotification('No recent decision available', 'error');\n                } catch (e) {\n                    showNotification('Failed to open investigation details', 'error');\n                }\n            })\n"
]
old = None
for cand in old_options:
    if cand in text:
        old = cand
        break
if old is None:
    raise SystemExit('inv block not found final python')
insight_block = "                    const row = j && (j.rows && j.rows[0] || j.events && j.events[0]);\\n                    const id = row ? (row.event_id || row.id) : null;\\n                    const insightPayload = row && (row.correlation_insights or row.get('correlationInsights')) if isinstance(row, dict) else None\\n"
# easier to compose new string manually
new = "            const invPanel = document.getElementById('investigationPanel');\\n            if (invPanel) invPanel.addEventListener('click', async () => {\\n                try {\\n                    const r = await (window.safeFetch || fetch)('/api/v1/decisions/recent?limit=1', { headers: authHeaders() });\\n                    let j = {};\\n                    try{ j = await r.json().catch(()=>({})); }catch(_){ }\\n                    if (!r.ok) {\\n                        const det = (j && (j.detail || j.error)) ? (j.detail || j.error) : ('HTTP ' + r.status);\\n                        showNotification('Failed to fetch recent decisions: ' + det, 'error');\\n                        return;\\n                    }\\n                    const row = j && (j.rows && j.rows[0] || j.events && j.events[0]);\\n                    const id = row ? (row.event_id || row.id) : null;\\n                    const insightPayload = row and ((row.get('correlation_insights') if isinstance(row, dict) else None) or (row.get('correlationInsights') if isinstance(row, dict) else None))\\n                    if (window.renderCorrelationInsightPanel) {\\n                        window.renderCorrelationInsightPanel(insightPayload);\\n                    }\\n                    if (id) openInvestigationDetails(id, { correlation_insights: insightPayload }); else showNotification('No recent decision available', 'error');\\n                } catch (e) {\\n                    showNotification('Failed to open investigation details', 'error');\\n                }\\n            });\\n"
