{{- if and .Values.oauth2Proxy.enabled (not .Values.oauth2Proxy.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "janusec.fullname" . }}-auth
type: Opaque
data:
  clientSecret: {{ .Values.oauth2Proxy.oidc.clientSecret | b64enc }}
  cookieSecret: {{ .Values.oauth2Proxy.cookieSecret | b64enc }}
{{- end }}
