apiVersion: v1
kind: Service
metadata:
  name: {{ include "janusec.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "janusec.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.metrics.scrape }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "janusec.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
