import os
import json

PATHS = [
    'src/core/reputation/',
    'src/core/risk_score.py',
    'src/core/scoring/',
    'src/core/secrets.py',
    'src/core/temporal/',
    'src/core/tenant_cleaner.py',
    'src/core/tenant_store.py',
    'src/core/threat_intel/',
    'src/core/threat_modeling/',
    'src/core/time_of_day.py',
    'src/core/tracing.py',
    'src/core/ueba/',
    'src/core/utils/',
    'src/core/writeback_dlq.py',
    'src/correlation/',
    'src/data/',
    'src/db/__pycache__/adapter.cpython-311.pyc',
    'src/db/__pycache__/migrations.cpython-311.pyc',
    'src/db/adapter.py',
    'src/db/migrations.py',
    'src/db/migrator.py',
    'src/dedup/',
    'src/detectors/',
    'src/embedding/',
    'src/enrichment/',
    'src/explain/',
    'src/features/',
    'src/feedback/',
    'src/graph/',
    'src/hunt/',
    'src/incident/',
    'src/incidents/',
    'src/ingest/',
    'src/ingestion/',
    'src/integrations/__pycache__/ai_providers.cpython-311.pyc',
    'src/integrations/__pycache__/bgp_client.cpython-311.pyc',
    'src/integrations/__pycache__/cert_checks.cpython-311.pyc',
    'src/integrations/__pycache__/crowdstrike_adapter.cpython-311.pyc',
    'src/integrations/__pycache__/eclipse_adapter.cpython-311.pyc',
    'src/integrations/__pycache__/llm_client.cpython-311.pyc',
    'src/integrations/__pycache__/misp_adapter.cpython-311.pyc',
    'src/integrations/__pycache__/misp_client.cpython-311.pyc',
    'src/integrations/__pycache__/opencti_adapter.cpython-311.pyc',
    'src/integrations/__pycache__/opencti_client.cpython-311.pyc',
    'src/integrations/__pycache__/qualys_client.cpython-311.pyc',
    'src/integrations/__pycache__/sbom.cpython-311.pyc',
    'src/integrations/__pycache__/sentinel_adapter.cpython-311.pyc',
    'src/integrations/__pycache__/splunk_adapter.cpython-311.pyc',
    'src/integrations/__pycache__/tenable_client.cpython-311.pyc',
    'src/integrations/__pycache__/threat_intel_client.cpython-311.pyc',
    'src/integrations/__pycache__/threat_intel_shim.cpython-311.pyc',
    'src/integrations/__pycache__/threat_intel_store.cpython-311.pyc',
    'src/integrations/__pycache__/vuln_enrichment.cpython-311.pyc',
    'src/integrations/bgp_client.py',
    'src/integrations/crowdstrike_adapter.py',
    'src/integrations/cyberstash_client.py',
    'src/integrations/eclipse_adapter.py',
    'src/integrations/kev_feed.py',
    'src/integrations/llm_client.py',
    'src/integrations/misp_adapter.py',
    'src/integrations/misp_client.py',
    'src/integrations/opencti_adapter.py',
    'src/integrations/opencti_client.py',
    'src/integrations/qualys_client.py',
    'src/integrations/sandbox/',
    'src/integrations/sbom.py',
    'src/integrations/sentinel_adapter.py',
    'src/integrations/splunk_adapter.py',
    'src/integrations/tenable_client.py',
    'src/integrations/threat_intel_client.py',
    'src/integrations/threat_intel_shim.py',
    'src/integrations/threat_intel_store.py',
    'src/integrations/vuln_enrichment.py',
    'src/jobs/',
    'src/live/__pycache__/asn_lookup.cpython-311.pyc',
    'src/live/__pycache__/zeek_adapter.cpython-311.pyc',
    'src/live/asn_lookup.py',
    'src/logging_config.py',
    'src/maintenance/__pycache__/redis_temporal_maintainer.cpython-311.pyc',
    'src/maintenance/redis_temporal_maintainer.py',
    'src/mapping/',
    'src/metrics/',
    'src/ml/',
    'src/models/',
    'src/modules/__pycache__/certificate_analysis.cpython-311.pyc',
    'src/modules/__pycache__/http_header_analysis.cpython-311.pyc',
    'src/modules/__pycache__/pilot_eval.cpython-311.pyc',
    'src/modules/certificate_analysis.py',
    'src/modules/compliance/',
    'src/modules/http_header_analysis.py',
    'src/modules/pilot_eval.py',
    'src/outbox/',
    'src/parsers/',
    'src/pipeline/',
    'src/plugins/',
    'src/privacy/',
    'src/reporting/__pycache__/',
    'src/repositories/__pycache__/calibration_proposals_repo.cpython-311.pyc',
    'src/repositories/__pycache__/decisions_repo_adapter.cpython-311.pyc',
    'src/repositories/__pycache__/decisions_repo_impl.cpython-311.pyc',
    'src/repositories/__pycache__/incidents_repo.cpython-311.pyc',
    'src/repositories/__pycache__/outbox_repo_sqlite.cpython-311.pyc',
    'src/repositories/__pycache__/report_snapshots_repo.cpython-311.pyc',
    'src/repositories/__pycache__/shared_inmemory.cpython-311.pyc',
    'src/repositories/calibration_proposals_repo.py',
    'src/repositories/decisions_repo_adapter.py',
    'src/repositories/decisions_repo_impl.py',
    'src/repositories/incidents_repo.py',
    'src/repositories/migrations.py',
    'src/repositories/outbox_repo.py',
    'src/repositories/outbox_repo_sqlite.py',
    'src/repositories/report_snapshots_repo.py',
    'src/repositories/shared_inmemory.py',
    'src/rules/',
    'src/secrets/',
    'src/security/__pycache__/auth.cpython-312.pyc',
    'src/security/__pycache__/egress_guard.cpython-311.pyc',
    'src/security/__pycache__/rbac.cpython-311.pyc',
    'src/security/egress_guard.py',
    'src/security/rbac.py',
    'src/signatures/',
    'src/soar/__init__.py',
    'src/soar/__pycache__/',
    'src/soar/actions/',
    'src/soar/connector_audit.py',
    'src/soar/connectors.py',
    'src/soar/dsl_schema.py',
    'src/soar/engine.py',
    'src/soar/playbook_loader.py',
    'src/soar/playbook_queue.py',
    'src/soar/playbook_queue_async.py',
    'src/soar/playbook_worker.py',
    'src/soar/runner.py',
    'src/tasks/',
    'src/telemetry/',
    'src/tests/',
    'src/tests_utils/',
    'src/tools/',
    'src/utils/',
    'src/workers/',
    'start_server.bat',
    'start_simple.py',
    'stress_run_summary.csv',
    'sultry_prd/',
    'sultrytai/',
    'suspicious_artifacts.csv',
    'taxonomy/',
    'temp_start_server.err',
    'temp_start_server.log',
    'temp_tail.txt',
    'terraform/',
    'test-results/',
    'test_asset.js',
    'test_janusec_capabilities.py',
    'test_scope.db',
    'test_sidecar_performance.py',
    'tests/__init__.py',
    'tests/__pycache__/',
]


def stat_path(p):
    info = {'path': p, 'exists': False}
    if os.path.exists(p):
        info['exists'] = True
        info['is_dir'] = os.path.isdir(p)
        try:
            info['size'] = os.path.getsize(p)
        except OSError:
            info['size'] = None
        info['type'] = 'dir' if info['is_dir'] else 'file'
    return info


def main():
    results = [stat_path(p) for p in PATHS]
    out = {
        'summary': {
            'checked': len(results),
            'found': sum(1 for r in results if r['exists']),
            'missing': sum(1 for r in results if not r['exists']),
        },
        'results': results,
    }
    print(json.dumps(out, indent=2))


if __name__ == '__main__':
    main()
