"""Generate a one-page SOC playbook PDF (printable).
Requires reportlab to be installed in the active environment.
"""
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
import time
import os

SOC_TEXT = '''
JanuSec SOC Playbook - Quick Reference

Purpose: Triage and respond to alerts generated by JanuSec ingestion pipeline.

1) Alert Intake
- Receive notification (PagerDuty/Slack) containing event_id, verdict, confidence.
- Inspect verdict and confidence immediately.

2) Initial Triage (SOC Analyst)
- If confidence >= 0.9 and verdict == malicious: escalate immediately.
- If confidence between 0.6-0.9: review evidence and enrich, escalate if justified.
- If confidence < 0.6: add to watchlist and schedule hunt.

3) Evidence Collection
- Retrieve chain-of-custody: GET /api/v1/chain/{event_id}
- Download artifacts from tabular sessions and preserve copies.

4) Enrichment
- Run threat intel lookups for IPs/hashes/URLs.
- Map to MITRE techniques and add tags.

5) Containment & Remediation
- For confirmed malicious activity: follow approved SOAR playbook (isolate host, block IP).
- For uncertainty: gather more artifacts and escalate to threat hunter.

6) Post-Incident
- Update the ticket with remediation actions and IOC lists.
- Submit feedback: POST /api/v1/feedback/factor to improve suppression.

Notes:
- Preserve original artifacts; log analyst actions in the ticket.
- If in doubt, escalate to senior analyst.
'''

def build(path: str):
    doc = SimpleDocTemplate(path, pagesize=LETTER, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph('JanuSec SOC Playbook - Quick Reference', styles['Title']))
    story.append(Spacer(1, 8))
    for line in SOC_TEXT.split('\n'):
        if not line.strip():
            story.append(Spacer(1,6))
            continue
        text = line.replace('+-','•').replace('-', '—')
        story.append(Paragraph(text, styles['Normal']))
    doc.build(story)

if __name__ == '__main__':
    outdir = os.path.join(os.getcwd(), 'artifacts')
    os.makedirs(outdir, exist_ok=True)
    out = os.path.join(outdir, f'soc_playbook_{int(time.time())}.pdf')
    build(out)
    print('Generated', out)
