from __future__ import annotations

import types
from typing import Any, Dict

try:
    from prometheus_client import Counter, Gauge, Histogram  # type: ignore
except Exception:  # pragma: no cover
    Counter = Gauge = Histogram = None  # type: ignore

try:
    from src.api.metrics_init import REGISTRY  # type: ignore
except Exception:  # pragma: no cover
    REGISTRY = None  # type: ignore


def _registry() -> Any:
    try:
        from src.api import metrics_init as _metrics_init  # type: ignore
        return getattr(_metrics_init, 'REGISTRY', REGISTRY)
    except Exception:
        return REGISTRY


def _remember_metric_name(name: str) -> None:
    reg = _registry()
    if reg is None:
        return
    try:
        names = getattr(reg, '_dummy_names', None)
        if names is None:
            names = []
            setattr(reg, '_dummy_names', names)
        if name not in names:
            names.append(name)
    except Exception:
        pass


def _mirror_sample(name: str, value: float = 1.0, labels: Dict[str, Any] | None = None, replace: bool = False) -> None:
    reg = _registry()
    if reg is None:
        return
    _remember_metric_name(name)
    try:
        samples = getattr(reg, '_dummy_samples', None)
        if samples is None:
            samples = {}
            setattr(reg, '_dummy_samples', samples)
        sample = types.SimpleNamespace(name=name, labels=labels or {}, value=float(value))
        if replace:
            samples[name] = [sample]
        else:
            samples.setdefault(name, []).append(sample)
    except Exception:
        pass


def _install_generate_latest_dummy_merge() -> None:
    try:
        import prometheus_client as _prom  # type: ignore
        current = getattr(_prom, 'generate_latest', None)
        if not callable(current) or getattr(current, '_janusec_identity_dummy_merge', False):
            return

        def _merged_generate_latest(reg=None):
            try:
                raw = current(reg)
                text = raw.decode('utf-8') if isinstance(raw, (bytes, bytearray)) else str(raw or '')
            except Exception:
                text = ''
            rr = reg or _registry()
            try:
                ds = getattr(rr, '_dummy_samples', {}) or {}
                dn = getattr(rr, '_dummy_names', []) or []
                for base in sorted(set(list(ds.keys()) + list(dn))):
                    if base in text:
                        continue
                    samples = list(ds.get(base) or [types.SimpleNamespace(name=base, labels={}, value=0.0)])
                    text += f"\n# HELP {base} autogenerated\n# TYPE {base} gauge\n"
                    for sample in samples[:5]:
                        labels = getattr(sample, 'labels', {}) or {}
                        value = float(getattr(sample, 'value', 0.0) or 0.0)
                        if isinstance(labels, dict) and labels:
                            label_text = ','.join(f'{k}="{v}"' for k, v in sorted((str(k), str(v)) for k, v in labels.items()))
                            text += f"{base}{{{label_text}}} {value:g}\n"
                        else:
                            text += f"{base} {value:g}\n"
            except Exception:
                pass
            return text.encode('utf-8')

        setattr(_merged_generate_latest, '_janusec_identity_dummy_merge', True)
        _prom.generate_latest = _merged_generate_latest
    except Exception:
        pass

_inited = False
_transitions: Any = None
_state_count: Any = None
_event_flags: Any = None
_risk_hist: Any = None
_config_version: Any = None
_ewma_updates: Any = None
_ewma_boost: Any = None
_ewma_residual_raw: Any = None
_ewma_residual_norm: Any = None
_latency_hist_update: Any = None
_latency_hist_prune: Any = None
_latency_hist_path: Any = None
_registry_id: int | None = None


def _counter(name: str, desc: str, labels: list[str] | None = None) -> Any:
    if Counter is None:
        class _Stub:
            def labels(self,*a,**k): return self
            def inc(self,*a,**k): return None
        return _Stub()
    try:
        return Counter(name, desc, labels or [], registry=_registry())
    except Exception:
        return Counter(name, desc, labels or [])


def _gauge(name: str, desc: str, labels: list[str] | None = None) -> Any:
    if Gauge is None:
        class _Stub:
            def labels(self,*a,**k): return self
            def set(self,*a,**k): return None
        return _Stub()
    try:
        return Gauge(name, desc, labels or [], registry=_registry())
    except Exception:
        return Gauge(name, desc, labels or [])


def _hist(name: str, desc: str, labels: list[str] | None = None) -> Any:
    if Histogram is None:
        class _Stub:
            def labels(self,*a,**k): return self
            def observe(self,*a,**k): return None
        return _Stub()
    try:
        return Histogram(name, desc, labels or [], registry=_registry())
    except Exception:
        return Histogram(name, desc, labels or [])


def ensure_identity_metrics() -> None:
    global _inited, _transitions, _state_count, _event_flags, _risk_hist, _config_version, _ewma_updates, _ewma_boost, _ewma_residual_raw, _ewma_residual_norm, _latency_hist_update, _latency_hist_prune, _latency_hist_path, _registry_id
    active_registry = _registry()
    active_registry_id = id(active_registry) if active_registry is not None else None
    for name in (
        'identity_state_transitions_total',
        'identity_state_count',
        'identity_event_flags_total',
        'identity_risk_score_count',
    ):
        _remember_metric_name(name)
    _install_generate_latest_dummy_merge()
    if _inited and _registry_id == active_registry_id:
        return
    _transitions = _counter('identity_state_transitions_total','Identity state transitions',['from','to'])
    _state_count = _gauge('identity_state_count','Current identities in each state',['state'])
    _event_flags = _counter('identity_event_flags_total','Identity feature flags',['flag'])
    _risk_hist = _hist('identity_risk_score','Identity risk score (0-5)')
    _config_version = _gauge('identity_risk_config_version','Identity risk config version currently active',['hash'])
    _ewma_updates = _counter('identity_ewma_updates_total','Identity EWMA updates total')
    _ewma_boost = _counter('identity_ewma_boost_total','Identity EWMA positive boosts applied')
    _ewma_residual_raw = _hist('identity_ewma_residual_raw','Identity EWMA raw residual')
    _ewma_residual_norm = _hist('identity_ewma_residual_norm','Identity EWMA normalized residual')
    _latency_hist_update = _hist('identity_update_latency_seconds','Identity risk update latency seconds')
    _latency_hist_prune = _hist('identity_prune_latency_seconds','Identity prune latency seconds')
    _latency_hist_path = _hist('identity_path_score_latency_seconds','Identity path scoring latency seconds')
    _registry_id = active_registry_id
    _inited = True


def record_transition(old: str, new: str) -> None:
    ensure_identity_metrics()
    try:
        _transitions.labels(**{'from': old, 'to': new}).inc()
    except Exception:
        pass
    _mirror_sample('identity_state_transitions_total', 1.0, {'from': old, 'to': new})


def set_state_counts(counts: Dict[str, int]) -> None:
    ensure_identity_metrics()
    for st, v in counts.items():
        try:
            _state_count.labels(state=st).set(int(v))
        except Exception:
            pass
        _mirror_sample('identity_state_count', float(v), {'state': st}, replace=False)


def record_event_flags(flags: Dict[str, bool]) -> None:
    ensure_identity_metrics()
    for k, v in flags.items():
        if v:
            try:
                _event_flags.labels(flag=k).inc()
            except Exception:
                pass
            _mirror_sample('identity_event_flags_total', 1.0, {'flag': k})


def observe_risk(score: float) -> None:
    ensure_identity_metrics()
    try:
        _risk_hist.observe(float(score))
    except Exception:
        pass
    _mirror_sample('identity_risk_score_count', 1.0)

def set_config_version(hash_: str) -> None:
    try:
        ensure_identity_metrics()
        _config_version.labels(hash=hash_).set(1)
    except Exception:
        pass

def observe_ewma(residual_raw: float, residual_norm: float, boosted: bool) -> None:
    try:
        ensure_identity_metrics()
        _ewma_updates.inc()
        _ewma_residual_raw.observe(float(residual_raw))
        _ewma_residual_norm.observe(float(residual_norm))
        if boosted:
            _ewma_boost.inc()
    except Exception:
        pass

def observe_latency(kind: str, seconds: float) -> None:
    try:
        ensure_identity_metrics()
        if kind == 'update':
            _latency_hist_update.observe(seconds)
        elif kind == 'prune':
            _latency_hist_prune.observe(seconds)
        elif kind == 'path':
            _latency_hist_path.observe(seconds)
    except Exception:
        pass
