from typing import Any, Dict, Optional
import io


def export_docx_bytes_from_report(payload: Dict[str, Any]) -> Optional[bytes]:
    """Return DOCX bytes from a report payload using python-docx when available.

    Returns None when python-docx is not installed or generation fails.
    Persona-aware: executive/mssp omit raw event rows; technical personas get a findings table.
    """
    try:
        from docx import Document
        from docx.shared import Pt
    except Exception:
        return None
    try:
        doc = Document()

        title = str(payload.get('title') or 'Janusec Investigation Report')
        doc.add_heading(title, 0)

        meta = payload.get('meta') or {}
        persona = str(meta.get('persona') or 'soc_analyst').lower()
        is_executive = persona in ('executive', 'mssp')
        audience_label = persona.replace('_', ' ').title()
        doc.add_paragraph(f'Audience: {audience_label}')

        session = str(payload.get('session_id') or '')
        if session:
            doc.add_paragraph(f'Session: {session}')

        recipients = meta.get('recipients') or []
        if recipients:
            doc.add_paragraph(f'Recipients: {", ".join(str(r) for r in recipients)}')

        # Executive Summary
        doc.add_heading('Executive Summary', 1)
        rows = payload.get('rows') or []
        summary = payload.get('summary') or {}
        verdict_stats = summary.get('verdict_stats') or {}
        sev_dist = summary.get('severity_distribution') or {}

        doc.add_paragraph(f'Total events analyzed: {len(rows)}')

        if verdict_stats:
            doc.add_heading('Verdict Distribution', 2)
            tbl = doc.add_table(rows=1, cols=2)
            tbl.style = 'Table Grid'
            hdr = tbl.rows[0].cells
            hdr[0].text = 'Verdict'
            hdr[1].text = 'Count'
            for k, v in list(verdict_stats.items())[:10]:
                r = tbl.add_row().cells
                r[0].text = str(k)
                r[1].text = str(v)

        if sev_dist:
            doc.add_heading('Severity Distribution', 2)
            tbl = doc.add_table(rows=1, cols=2)
            tbl.style = 'Table Grid'
            hdr = tbl.rows[0].cells
            hdr[0].text = 'Severity'
            hdr[1].text = 'Count'
            for sev, cnt in sev_dist.items():
                r = tbl.add_row().cells
                r[0].text = str(sev)
                r[1].text = str(cnt)

        # Correlation / HopGraph
        corr = payload.get('correlation') or {}
        if isinstance(corr, dict) and corr.get('verdict'):
            doc.add_heading('Correlation Analysis', 1)
            doc.add_paragraph(f'Verdict: {corr.get("verdict")}')
            if corr.get('confidence') is not None:
                doc.add_paragraph(f'Confidence: {corr.get("confidence")}')
            if corr.get('narrative'):
                doc.add_paragraph(str(corr.get('narrative')))

        # MITRE ATT&CK
        top_mitre = payload.get('top_mitre') or []
        if top_mitre:
            doc.add_heading('Top MITRE ATT&CK Techniques', 1)
            tbl = doc.add_table(rows=1, cols=2)
            tbl.style = 'Table Grid'
            hdr = tbl.rows[0].cells
            hdr[0].text = 'Technique'
            hdr[1].text = 'Count'
            for item in top_mitre[:15]:
                r = tbl.add_row().cells
                r[0].text = str(item.get('technique') or '')
                r[1].text = str(item.get('count') or 0)

        # Key Findings table — omit for executive/mssp to keep deliverable clean
        if rows and not is_executive:
            doc.add_heading('Key Findings', 1)
            shown = min(len(rows), 25)
            doc.add_paragraph(f'Showing {shown} of {len(rows)} events.')
            tbl = doc.add_table(rows=1, cols=4)
            tbl.style = 'Table Grid'
            hdr = tbl.rows[0].cells
            hdr[0].text = 'Host'
            hdr[1].text = 'Process'
            hdr[2].text = 'Verdict'
            hdr[3].text = 'MITRE'
            for row in rows[:shown]:
                r = tbl.add_row().cells
                r[0].text = str(row.get('host') or row.get('hostname') or '')
                r[1].text = str(row.get('process_name') or row.get('process') or '')
                r[2].text = str(row.get('verdict') or row.get('Verdict') or '')
                mitre = row.get('mitre') or []
                r[3].text = ', '.join(mitre[:3]) if isinstance(mitre, list) else str(mitre or '')

        doc.add_paragraph()
        doc.add_paragraph('Generated by Janusec reporting pipeline.')

        buf = io.BytesIO()
        doc.save(buf)
        return buf.getvalue()
    except Exception:
        return None


def export_pdf_bytes_from_html(html: str) -> Optional[bytes]:
    """Return PDF bytes generated from HTML.

    Priority order:
      1. xhtml2pdf  — uses ReportLab internally; best Windows compatibility.
      2. WeasyPrint  — better CSS fidelity but requires GTK/Pango native libs.
      3. Playwright  — Chromium headless fallback.
    Returns None when no engine is available or all fail.
    """
    # 1. xhtml2pdf / ReportLab (preferred — no native lib deps on Windows)
    try:
        import io as _io1
        from xhtml2pdf import pisa  # type: ignore
        _buf = _io1.BytesIO()
        _status = pisa.CreatePDF(html.encode('utf-8'), dest=_buf)
        if not _status.err and _buf.tell() > 1024:
            _buf.seek(0)
            return _buf.read()
    except ImportError:
        pass  # not installed — try WeasyPrint
    except Exception:
        pass  # generation error — try WeasyPrint

    # 2. WeasyPrint fallback (requires GTK/Pango native libraries)
    try:
        import warnings as _w
        with _w.catch_warnings():
            _w.simplefilter("ignore")
            from weasyprint import HTML as _WP_HTML
            pdf = _WP_HTML(string=html).write_pdf()
            if pdf and len(pdf) > 1024:
                return pdf
    except ImportError:
        pass
    except Exception:
        pass

    # 3. Playwright fallback (requires playwright install chromium)
    return _export_pdf_playwright(html)


def _export_pdf_playwright(html: str) -> Optional[bytes]:
    """Generate PDF bytes via Playwright (Chromium headless).

    Writes HTML to a temporary file, opens it in Chromium, and exports PDF.
    Requires: pip install playwright && playwright install chromium
    """
    import tempfile
    import os as _os
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        return None
    try:
        with tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False, encoding='utf-8') as tmp:
            tmp.write(html)
            tmp_path = tmp.name
        try:
            with sync_playwright() as p:
                browser = p.chromium.launch()
                page = browser.new_page()
                page.goto(f'file:///{tmp_path.replace(chr(92), "/")}')
                page.wait_for_load_state('networkidle')
                pdf_bytes = page.pdf(format='A4', print_background=True)
                browser.close()
            return pdf_bytes
        finally:
            try:
                _os.unlink(tmp_path)
            except Exception:
                pass
    except Exception:
        return None


def export_docx_bytes_from_html(html: str, reference_docx: Optional[str] = None) -> Optional[bytes]:
    """Convert HTML to DOCX bytes.

    Uses Pandoc (recommended: `choco install pandoc` or https://pandoc.org) when
    available for highest-fidelity conversion. Falls back to the htmldocx/python-docx
    library path when Pandoc is not found.

    Args:
        html: HTML string to convert.
        reference_docx: Optional path to a reference .docx for branding/styles.
            Passed to pandoc as --reference-doc. Defaults to
            JANUSEC_DOCX_REFERENCE env var if set.

    Returns:
        DOCX bytes, or None if conversion is not available.
    """
    import shutil
    import subprocess
    import tempfile
    import os as _os

    ref = reference_docx or _os.getenv('JANUSEC_DOCX_REFERENCE')

    # 1. Pandoc path (preferred)
    pandoc = shutil.which('pandoc')
    if pandoc:
        try:
            with tempfile.NamedTemporaryFile(mode='w', suffix='.html', delete=False, encoding='utf-8') as tmp_in:
                tmp_in.write(html)
                in_path = tmp_in.name
            out_fd, out_path = tempfile.mkstemp(suffix='.docx')
            _os.close(out_fd)
            try:
                cmd = [pandoc, '-f', 'html', '-t', 'docx', '-o', out_path, in_path]
                if ref and _os.path.isfile(ref):
                    cmd += [f'--reference-doc={ref}']
                result = subprocess.run(cmd, capture_output=True, timeout=60)
                if result.returncode == 0:
                    with open(out_path, 'rb') as fh:
                        return fh.read()
            finally:
                try:
                    _os.unlink(in_path)
                except Exception:
                    pass
                try:
                    _os.unlink(out_path)
                except Exception:
                    pass
        except Exception:
            pass  # fall through to library path

    # 2. htmldocx + python-docx library path
    try:
        from docx import Document as _Document
        from htmldocx import HtmlToDocx  # type: ignore
        doc = _Document()
        parser = HtmlToDocx()
        parser.add_html_to_document(html, doc)
        buf = io.BytesIO()
        doc.save(buf)
        return buf.getvalue()
    except ImportError:
        pass
    except Exception:
        pass

    return None




def make_pdf_stream_bytes(html: str) -> bytes:
    pdf = export_pdf_bytes_from_html(html)
    if pdf is None:
        raise RuntimeError('pdf_generation_failed: install weasyprint or playwright')
    return pdf


def make_docx_stream_bytes(html, reference_docx=None):
    docx = export_docx_bytes_from_html(html, reference_docx=reference_docx)
    if docx is None:
        raise RuntimeError('docx_generation_failed: install pandoc or htmldocx+python-docx')
    return docx
